// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDomlhOeSQZuax56a5IAhPUkRib5FpzxEI',
    appId: '1:1043876365760:web:42dfb45e858ceb8965f425',
    messagingSenderId: '1043876365760',
    projectId: 'staybnb-44f04',
    authDomain: 'staybnb-44f04.firebaseapp.com',
    storageBucket: 'staybnb-44f04.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzrB5MQEFkWVEDVKJw3yiu5qiLYwwRfkU',
    appId: '1:1043876365760:android:b2c2ad6b81632d9165f425',
    messagingSenderId: '1043876365760',
    projectId: 'staybnb-44f04',
    storageBucket: 'staybnb-44f04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqELv02BqeoadWn0mtVYfLaBvSEdHS1Zg',
    appId: '1:1043876365760:ios:d2870b4e2ade3cb265f425',
    messagingSenderId: '1043876365760',
    projectId: 'staybnb-44f04',
    storageBucket: 'staybnb-44f04.appspot.com',
    iosBundleId: 'com.example.staybnb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqELv02BqeoadWn0mtVYfLaBvSEdHS1Zg',
    appId: '1:1043876365760:ios:d2870b4e2ade3cb265f425',
    messagingSenderId: '1043876365760',
    projectId: 'staybnb-44f04',
    storageBucket: 'staybnb-44f04.appspot.com',
    iosBundleId: 'com.example.staybnb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDomlhOeSQZuax56a5IAhPUkRib5FpzxEI',
    appId: '1:1043876365760:web:860c0eb3b25e72fa65f425',
    messagingSenderId: '1043876365760',
    projectId: 'staybnb-44f04',
    authDomain: 'staybnb-44f04.firebaseapp.com',
    storageBucket: 'staybnb-44f04.appspot.com',
  );
}
